// src/context/LanguageContext.jsx
import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';
import { doc, getDoc, updateDoc } from 'firebase/firestore';
import { auth, db } from '../firebase';

const LanguageContext = createContext(null);

export const TRANSLATIONS = {
  'pt-BR': {
    // Navigation / Tabs
    'tab.backlog': 'Backlog',
    'tab.stats': 'Stats',
    'tab.social': 'Social',
    'tab.trophies': 'Troféus',
    'tab.profile': 'Perfil',

    // Main Columns / Categories
    'col.playing': 'Jogando agora',
    'col.backlog': 'Na Fila',
    'col.installed': 'Instalados',
    'col.completed': 'Zerados',
    'col.wishlist': 'Lista de Desejos',
    'col.dropped': 'Abandonados',
    'col.paused': 'Pausados',
    'cat.playing': '🔥 Jogando Agora',
    'cat.installed': '💾 Instalados',
    'cat.backlog': '⏳ Na Fila',
    'cat.zerados': '✅ Zerados',
    'cat.desejados': '🌟 Lista de Desejos',
    'cat.desc_playing': 'O que está ocupando seu tempo agora.',
    'cat.desc_backlog': 'Sua fila de próximas aventuras.',
    'cat.desc_installed': 'Prontos para começar quando você quiser.',
    'cat.desc_zerados': 'A história daquilo que você já conquistou.',
    'cat.desc_desejados': 'Jogos que ainda estão no seu radar.',

    // Home / Library
    'home.library': 'Sua biblioteca',
    'home.hello': 'Olá',
    'home.subtitle': 'Escolha a próxima aventura ou reorganize sua fila.',
    'home.add_game': 'Adicionar jogo',
    'home.in_collection': 'Na coleção',
    'home.completion': 'Conclusão',
    'home.time_in_queue': 'Tempo na fila',
    'home.pace_30d': 'Ritmo · 30 dias',
    'home.games_suffix': ' jogos',
    'home.completed_suffix': ' zerados',
    'home.no_games': 'Nenhum jogo aqui',
    'home.drag_here': 'Arraste para cá',
    'home.drop_in': 'Solte em',
    'home.focus_mode': 'Modo Foco',
    'home.view_all': 'Ver todos',

    // Game List Modern
    'list.back': 'Voltar',
    'list.collection': 'Coleção',
    'list.search_placeholder': 'Buscar nesta categoria...',
    'list.all_years': 'Todos os anos',
    'list.order_by': 'Ordenar por',
    'list.order_manual': 'Ordem manual',
    'list.order_date_desc': 'Mais recentes primeiro',
    'list.order_date_asc': 'Mais antigos primeiro',
    'list.order_rating_desc': 'Maior nota',
    'list.order_hours_desc': 'Mais longos',
    'list.order_name': 'Nome (A-Z)',
    'list.only_platinums': 'Apenas platinas',
    'list.export_image': 'Exportar imagem',
    'list.reorder': 'Reordenar',
    'list.done_reorder': 'Concluir',
    'list.total_hours': 'Horas estimadas',
    'list.avg_rating': 'Nota média',
    'list.platinums': 'Platinas',
    'list.games_count': 'jogos',
    'list.no_games': 'Nenhum jogo nesta categoria',
    'list.no_games_filter': 'Nenhum jogo corresponde aos filtros',
    'list.no_date': 'Sem data',

    // Game Detail Modern
    'detail.back': 'Voltar',
    'detail.heading': 'Detalhes do jogo',
    'detail.completed_adventure': 'Aventura concluída',
    'detail.in_journey': 'Na sua jornada',
    'detail.completed_on': 'Concluído em',
    'detail.with_score': ', com nota',
    'detail.estimated_hours_suffix': 'horas estimadas',
    'detail.no_time_yet': 'Tempo ainda não informado',
    'detail.reopen_btn': 'Reabrir jornada',
    'detail.finish_btn': 'Marcar como zerado',
    'detail.edit_btn': 'Editar informações',
    'detail.overview': 'Visão geral',
    'detail.review': 'Review',
    'detail.notes': 'Anotações',
    'detail.platform': 'Plataforma',
    'detail.genre': 'Gênero',
    'detail.time_to_beat': 'Duração',
    'detail.completion_date': 'Conclusão',
    'detail.my_rating': 'Avaliação',
    'detail.platinum': 'Platina',
    'detail.stat_status': 'Status',
    'detail.stat_time': 'Tempo',
    'detail.stat_rating': 'Nota',
    'detail.stat_conclusion': 'Conclusão',
    'detail.stat_open': 'Em aberto',
    'detail.sheet': 'Ficha da jornada',
    'detail.my_review': 'Sua avaliação pessoal',
    'detail.my_notes': 'Notas pessoais',
    'detail.move_to': 'Mover para',
    'detail.organize': 'Organize sua coleção',
    'detail.not_informed': 'Não informada',
    'detail.not_informed_m': 'Não informado',
    'detail.no_review_yet': 'Ainda sem avaliação',
    'detail.confirm_delete': 'Remover “{nome}” da sua coleção?',
    'detail.copied': 'Texto copiado.',
    'detail.share_error': 'Não foi possível compartilhar.',
    'detail.moved_to': 'Movido para',

    // Add / Edit Game Modal
    'modal.add_title': 'Adicionar Jogo',
    'modal.edit_title': 'Editar Jogo',
    'modal.add_subtitle': 'Preencha os dados',
    'modal.edit_subtitle': 'Atualize as informações',
    'modal.search_igdb': 'Buscar no IGDB',
    'modal.search_placeholder': 'Digite o nome do jogo...',
    'modal.search_hint': 'As sugestões aparecem automaticamente a partir de 2 caracteres.',
    'modal.searching': 'Buscando...',
    'modal.nothing_found': 'Nada encontrado',
    'modal.cover': 'Capa',
    'modal.cover_change': 'Alterar',
    'modal.cover_add': 'Adicionar',
    'modal.name': 'Nome',
    'modal.name_placeholder': 'Nome do jogo',
    'modal.already_in_collection': 'Este jogo já está na coleção',
    'modal.can_add_other_edition': 'Você ainda pode adicionar outra edição.',
    'modal.status': 'Status',
    'modal.genre': 'Gênero',
    'modal.genre_select': 'Selecione',
    'modal.hours_label': 'Horas Estimadas',
    'modal.hours_for_beating': 'h para zerar',
    'modal.hours_shortcuts': 'Atalhos:',
    'modal.platforms': 'Plataformas',
    'modal.your_rating': 'Sua Nota',
    'modal.rating_hint': 'Clique para avaliar · opcional',
    'modal.custom_date': 'Data personalizada',
    'modal.custom_date_question': 'Quando você zerou esse jogo?',
    'modal.custom_date_hint': 'Zerado em outra data? Adicione aqui',
    'modal.finished_at': 'Zerado em:',
    'modal.platinum_title': 'Platinado / 100% Completo',
    'modal.platinum_desc': 'Marque se você conquistou todas as conquistas',
    'modal.tags': 'Tags Personalizadas',
    'modal.notes': 'Anotações (Opcional)',
    'modal.notes_placeholder': 'Ex: Tenho a continuação no PS5; Pegar troféu X...',
    'modal.save': 'Salvar Jogo',
    'modal.save_changes': 'Salvar Alterações',

    // Review Modal
    'review.title': 'Avaliar Jogo',
    'review.congrats': 'Parabéns por zerar:',
    'review.your_rating': 'Sua Nota:',
    'review.rating_instructions': 'Clique no ícone para selecionar a nota (1 a 10).',
    'review.finished_date': 'Data da conclusão',
    'review.platinum_title': 'Platinado / 100% Completo',
    'review.platinum_desc': 'Conquistei todas as conquistas',
    'review.comments': 'Comentários (Opcional)',
    'review.comments_placeholder': 'Ex: Uma obra-prima! O final me fez chorar...',
    'review.finish_btn': 'Finalizar e Marcar como Zerado',

    // Stats / Progress Screen
    'stats.journey': 'Sua jornada',
    'stats.title': 'Estatísticas',
    'stats.subtitle': 'Seu jeito de jogar traduzido em números.',
    'stats.est_hours': 'Horas estimadas',
    'stats.cataloged_games': 'jogos catalogados',
    'stats.completed_games': 'Jogos zerados',
    'stats.of_collection': 'da coleção',
    'stats.avg_score': 'Nota média',
    'stats.rated_between': 'entre jogos avaliados',
    'stats.platinums': 'Platinas',
    'stats.completed_100': 'jogos completados em 100%',
    'stats.collection_dist': 'Distribuição da coleção',
    'stats.where_games_are': 'Onde estão seus jogos agora',
    'stats.add_games_hint': 'Adicione jogos para visualizar a distribuição.',
    'stats.fav_genres': 'Gêneros favoritos',
    'stats.based_on_completed': 'Com base nos jogos que você zerou',
    'stats.genres_appear_hint': 'Os gêneros aparecem quando você conclui jogos.',
    'stats.recently_completed': 'Zerados recentemente',
    'stats.recent_achievements': 'Suas últimas conquistas',
    'stats.no_completed_yet': 'Nenhum jogo zerado ainda.',
    'stats.plat_single': 'Jogo platinado',
    'stats.plat_multi': 'Jogos platinados',
    'stats.plat_pct_hint': 'dos jogos zerados chegaram aos 100%.',
    'stats.games_count': 'jogos',
    'stats.game_count_single': 'jogo',

    // Trophies / Enhanced Achievements
    'trophies.subtitle': 'Sua coleção de feitos',
    'trophies.title': 'Troféus',
    'trophies.count_desc': 'conquistas desbloqueadas em',
    'trophies.games': 'jogos.',
    'trophies.tier_platina': 'Platina',
    'trophies.tier_ouro': 'Ouro',
    'trophies.tier_prata': 'Prata',
    'trophies.tier_bronze': 'Bronze',
    'trophies.overall_progress': 'Progresso geral',
    'trophies.achievements_waiting': 'conquistas ainda esperam por você.',
    'trophies.earned_xp': 'XP conquistados',
    'trophies.xp_desc': 'Somando todos os seus feitos desbloqueados.',

    // AI Modal & Badge
    'ai.badge_button': 'IA em breve',
    'ai.badge': 'Em Breve',
    'ai.title': 'Recomendações com IA',
    'ai.headline': 'Em breve teremos recomendações de jogos personalizados de acordo com o seu gosto!',
    'ai.feature1_title': 'Baseado no que você zerou e amou',
    'ai.feature1_desc': 'Analisa suas notas altas e preferências reais de gameplay.',
    'ai.feature2_title': 'Alinhado ao seu tempo livre',
    'ai.feature2_desc': 'Sugere jogos de acordo com quantas horas você quer investir.',
    'ai.feature3_title': 'Descubra pérolas escondidas',
    'ai.feature3_desc': 'Títulos que você vai adorar e talvez nem saiba que existem.',
    'ai.got_it': 'Entendido, mal posso esperar!',

    // Navigation desktop
    'nav.completed_games': 'jogos zerados',

    // Settings
    'settings.title': 'Configurações',
    'settings.subtitle': 'Personalize sua experiência',
    'settings.theme': 'Tema de Cores',
    'settings.language': 'Idioma',
    'settings.lang_pt': 'Português (Brasil)',
    'settings.lang_en': 'English',
    'settings.preview': 'Preview',
    'settings.preview_desc': 'Assim vai ficar o seu app',
    'settings.apply_theme': 'Aplicar Tema',
    'settings.terms': 'Termos de Uso',
    'settings.privacy': 'Privacidade',

    // Profile & Public Profile
    'profile.title': 'Meu perfil',
    'profile.my_profile': 'Meu perfil',
    'profile.back': 'Voltar',
    'profile.player_profile': 'Perfil do jogador',
    'profile.edit': 'Editar perfil',
    'profile.edit_profile': 'Editar Perfil',
    'profile.update_info': 'Atualize suas informações',
    'profile.display_name': 'Nome de exibição *',
    'profile.name_placeholder': 'Seu nome no app',
    'profile.bio': 'Bio (opcional)',
    'profile.bio_placeholder': 'Uma frase sobre você como gamer...',
    'profile.email': 'E-mail (Google)',
    'profile.save_changes': 'Salvar Alterações',
    'profile.logout': 'Sair',
    'profile.public_title': 'Perfil Público',
    'profile.public_subtitle': 'Compartilhe seu backlog',
    'profile.your_username': 'Seu username',
    'profile.copy_link': 'Copiar link',
    'profile.copied': 'Copiado!',
    'profile.view_widget': 'Ver widget',
    'profile.auto_saved': 'Salvo automaticamente',
    'profile.saving': 'Salvando...',
    'profile.username_short': 'Username muito curto (mín. 3 chars)',
    'profile.username_taken': 'Esse username já está em uso.',
    'profile.stats_completed': 'Zerados',
    'profile.stats_platinums': 'Platinas',
    'profile.stats_avg_rating': 'Nota média',
    'profile.stats_hours': 'Horas jogadas',
    'profile.stats_completion': 'Taxa de conclusão',
    'profile.favorites': 'Favoritos',
    'profile.fav_games': 'Jogos Favoritos',
    'profile.select_favs': 'selecionados',
    'profile.search_fav': 'Buscar jogo…',
    'profile.no_fav_results': 'Nenhum resultado',
    'profile.confirm_selection': 'Confirmar Seleção',
    'profile.add_favorites': 'Adicione seus favoritos',
    'profile.highlight_up_to_5': 'Destaque até 5 jogos especiais',
    'profile.fav_num_1': '⭐ Favorito #1',
    'profile.platinum_badge': '🏆 Platina',
    'profile.stats': 'Estatísticas',
    'profile.completion_rate': 'Taxa de Conclusão',
    'profile.games_completed_ratio': '{total} jogos · {finished} zerados',
    'profile.highlights': 'Destaques',
    'profile.fav_platform': 'Plataforma favorita',
    'profile.fav_genre': 'Gênero favorito',
    'profile.total_games': 'Total de jogos',
    'profile.avg_rating': 'Nota média',
    'profile.recently_completed': 'Zerados Recentemente',
    'profile.badges_title': 'Insígnias',
    'profile.badges_unlocked': 'desbloqueadas',
    'profile.theme_btn': 'Tema',
    'profile.theme_btn_sub': 'Personalizar cores',
    'profile.name_and_bio': 'Nome e bio',
    'profile.stat_zerados': 'Zerados',
    'profile.stat_total': 'Total',
    'profile.stat_horas': 'Horas',
    'profile.stat_platinas': 'Platinas',
    'profile.stat_notamed': 'Nota Méd.',
    'profile.badges': 'Conquistas',
    'profile.playing_now': 'Jogando agora',
    'profile.recent_completed': 'Últimos zerados',
    'profile.no_playing': 'Nenhum jogo em andamento no momento.',
    'profile.no_completed': 'Nenhum jogo concluído ainda.',
    'profile.not_found': 'Perfil não encontrado',
    'profile.not_found_desc': 'O usuário que você procura não existe ou alterou o nome.',
    'profile.create_backlog_cta': 'Crie seu Backlog também',
    'profile.level': 'Nível',
    'profile.next_level_in': 'jogos para o próximo nível',

    // Social / Friends
    'social.title': 'Comunidade Gamer',
    'social.my_code': 'Meu Código de Amizade',
    'social.copied': 'Copiado!',
    'social.copy': 'Copiar',
    'social.tab_friends': 'Amigos',
    'social.tab_ranking': 'Ranking',
    'social.tab_feed': 'Feed',
    'social.tab_requests': 'Pedidos',
    'social.tab_search': 'Buscar',
    'social.no_friends': 'Nenhum amigo adicionado ainda.',
    'social.add_first_friend': 'Adicione amigos para ver o progresso deles!',
    'social.search_placeholder': 'Digite o código de amizade...',
    'social.search_btn': 'Buscar',

    // Common actions
    'action.save': 'Salvar',
    'action.cancel': 'Cancelar',
    'action.close': 'Fechar',
    'action.search': 'Buscar jogos...',
    'action.add_game': 'Adicionar Jogo',
    'action.filter': 'Filtrar',

    // Search Modal
    'search.placeholder': 'Buscar por nome, gênero, plataforma...',
    'search.hint': 'Digite para buscar na sua coleção',
    'search.not_found': 'Nenhum jogo encontrado para',
    'search.not_found_hint': 'Tente buscar por outro termo ou gênero',
    'search.esc_hint': 'ESC para fechar',

    // Next Game Suggestion
    'next_game.badge': 'Próximo Jogo',
    'next_game.very_short': 'Rapidinho',
    'next_game.short': 'Curto',
    'next_game.medium': 'Médio',
    'next_game.long': 'Longo',
    'next_game.no_estimate': 'Sem estimativa de tempo',
    'next_game.another_suggestion': 'Outra sugestão',
    'next_game.play': 'Jogar',
    'next_game.dismiss': 'Dispensar',

    // All Achievements
    'ach.first_game.title': 'Primeira Vitória',
    'ach.first_game.desc': 'Marque o seu primeiro jogo como zerado.',
    'ach.first_backlog.title': 'Começo de Coleção',
    'ach.first_backlog.desc': 'Adicione 5 jogos à sua coleção.',
    'ach.first_review.title': 'Crítico Iniciante',
    'ach.first_review.desc': 'Avalie seu primeiro jogo com uma nota.',
    'ach.five_games.title': 'Colecionador Nível 1',
    'ach.five_games.desc': 'Zere 5 jogos no total.',
    'ach.ten_games.title': 'Veterano',
    'ach.ten_games.desc': 'Zere 10 jogos no total.',
    'ach.twenty_five_games.title': 'Caçador de Finais',
    'ach.twenty_five_games.desc': 'Zere 25 jogos no total.',
    'ach.fifty_games.title': 'Lendário',
    'ach.fifty_games.desc': 'Zere 50 jogos. Uma lenda viva.',
    'ach.full_backlog.title': 'Backlog Cheio',
    'ach.full_backlog.desc': 'Tenha 15 ou mais jogos listados.',
    'ach.wishlist_10.title': 'Sonhador',
    'ach.wishlist_10.desc': 'Adicione 10 jogos à lista de desejos.',
    'ach.queue_buster.title': 'Destruidor de Filas',
    'ach.queue_buster.desc': 'Tenha 20+ jogos entre backlog e instalados.',
    'ach.multi_platform.title': 'Gamer Multiplataforma',
    'ach.multi_platform.desc': 'Zere jogos em 3 plataformas diferentes.',
    'ach.first_platinum.title': 'Completista',
    'ach.first_platinum.desc': 'Consiga sua primeira platina.',
    'ach.five_platinums.title': 'Caçador de Platinas',
    'ach.five_platinums.desc': 'Consiga 5 platinas.',
    'ach.ten_platinums.title': 'Mestre do 100%',
    'ach.ten_platinums.desc': 'Consiga 10 platinas.',
    'ach.perfect_score.title': 'Obra-Prima',
    'ach.perfect_score.desc': 'Dê nota 10 para um jogo.',
    'ach.three_perfect.title': 'Crítico Exigente',
    'ach.three_perfect.desc': 'Dê nota 10 para 3 jogos.',
    'ach.average_8.title': 'Bom Gosto',
    'ach.average_8.desc': 'Mantenha nota média ≥ 8 com 5+ avaliações.',
    'ach.honest_critic.title': 'Crítico Honesto',
    'ach.honest_critic.desc': 'Dê uma nota ≤ 4 para um jogo.',
    'ach.rpg_master.title': 'Mestre dos RPGs',
    'ach.rpg_master.desc': 'Zere 3 jogos do gênero RPG.',
    'ach.action_hero.title': 'Herói de Ação',
    'ach.action_hero.desc': 'Zere 3 jogos do gênero Ação.',
    'ach.fps_soldier.title': 'Soldado FPS',
    'ach.fps_soldier.desc': 'Zere 3 jogos do gênero FPS.',
    'ach.genre_master.title': 'Especialista de Gênero',
    'ach.genre_master.desc': 'Zere 5 jogos do mesmo gênero.',
    'ach.fifty_hours.title': 'Dedicado',
    'ach.fifty_hours.desc': 'Acumule 50 horas nos jogos zerados.',
    'ach.two_hundred_hours.title': 'Maratonista',
    'ach.two_hundred_hours.desc': 'Acumule 200 horas nos jogos zerados.',
    'ach.five_hundred_hours.title': 'No-Lifer',
    'ach.five_hundred_hours.desc': 'Acumule 500 horas nos jogos zerados.',
    'ach.one_thousand_hours.title': 'O Escolhido',
    'ach.one_thousand_hours.desc': 'Acumule 1000 horas de jornada.',

    // Landing / Login
    'landing.security_badge': 'Seus dados sincronizados com segurança',
    'landing.badge': 'Sua próxima aventura começa aqui',
    'landing.headline_1': 'Menos tempo escolhendo.',
    'landing.headline_grad': 'Mais tempo jogando.',
    'landing.subtitle': 'Organize sua coleção, acompanhe conquistas e encontre o jogo certo para cada momento — sem transformar diversão em planilha.',
    'landing.bullet1': 'Backlog em um só lugar',
    'landing.bullet2': 'Estatísticas automáticas',
    'landing.bullet3': 'Sugestões personalizadas',
    'landing.continue_google': 'Continuar com Google',
    'landing.login_note': 'Login rápido e seguro. Nada de senha extra para lembrar.',
    'landing.panel_title': 'Seu painel',
    'landing.panel_subtitle': 'Tudo sob controle',
    'landing.panel_games_count': '24 jogos',
    'landing.status_playing': 'Jogando',
    'landing.status_queue': 'Na fila',
    'landing.status_completed': 'Zerados',
    'landing.feat1_title': 'Backlog organizado',
    'landing.feat1_desc': 'Tudo que você quer jogar, sem perder o contexto.',
    'landing.feat2_title': 'Progresso visível',
    'landing.feat2_desc': 'Metas, histórico e estatísticas em um só lugar.',
    'landing.feat3_title': 'Escolhas mais fáceis',
    'landing.feat3_desc': 'Sugestões inteligentes para decidir o próximo jogo.',
    'landing.copyright': '© {year} XpLog. Todos os direitos reservados.',
    'landing.terms': 'Termos de Uso',
    'landing.privacy': 'Política de Privacidade',
  },
  'en': {
    // Navigation / Tabs
    'tab.backlog': 'Backlog',
    'tab.stats': 'Stats',
    'tab.social': 'Social',
    'tab.trophies': 'Trophies',
    'tab.profile': 'Profile',

    // Main Columns / Categories
    'col.playing': 'Playing now',
    'col.backlog': 'In Queue',
    'col.installed': 'Installed',
    'col.completed': 'Completed',
    'col.wishlist': 'Wishlist',
    'col.dropped': 'Dropped',
    'col.paused': 'Paused',
    'cat.playing': '🔥 Playing Now',
    'cat.installed': '💾 Installed',
    'cat.backlog': '⏳ In Queue',
    'cat.zerados': '✅ Completed',
    'cat.desejados': '🌟 Wishlist',
    'cat.desc_playing': 'What is keeping you busy right now.',
    'cat.desc_backlog': 'Your queue of upcoming adventures.',
    'cat.desc_installed': 'Ready to play whenever you want.',
    'cat.desc_zerados': 'The story of what you have accomplished.',
    'cat.desc_desejados': 'Games that are still on your radar.',

    // Home / Library
    'home.library': 'Your library',
    'home.hello': 'Hello',
    'home.subtitle': 'Pick your next adventure or reorganize your queue.',
    'home.add_game': 'Add game',
    'home.in_collection': 'In collection',
    'home.completion': 'Completion',
    'home.time_in_queue': 'Time in queue',
    'home.pace_30d': 'Pace · 30 days',
    'home.games_suffix': ' games',
    'home.completed_suffix': ' completed',
    'home.no_games': 'No games here',
    'home.drag_here': 'Drag here',
    'home.drop_in': 'Drop in',
    'home.focus_mode': 'Focus Mode',
    'home.view_all': 'View all',

    // Game List Modern
    'list.back': 'Back',
    'list.collection': 'Collection',
    'list.search_placeholder': 'Search in this category...',
    'list.all_years': 'All years',
    'list.order_by': 'Sort by',
    'list.order_manual': 'Manual order',
    'list.order_date_desc': 'Most recent first',
    'list.order_date_asc': 'Oldest first',
    'list.order_rating_desc': 'Highest rating',
    'list.order_hours_desc': 'Longest first',
    'list.order_name': 'Name (A-Z)',
    'list.only_platinums': 'Only platinums',
    'list.export_image': 'Export image',
    'list.reorder': 'Reorder',
    'list.done_reorder': 'Done',
    'list.total_hours': 'Estimated hours',
    'list.avg_rating': 'Average rating',
    'list.platinums': 'Platinums',
    'list.games_count': 'games',
    'list.no_games': 'No games in this category',
    'list.no_games_filter': 'No games match your filters',
    'list.no_date': 'No date',

    // Game Detail Modern
    'detail.back': 'Back',
    'detail.heading': 'Game details',
    'detail.completed_adventure': 'Adventure completed',
    'detail.in_journey': 'In your journey',
    'detail.completed_on': 'Completed on',
    'detail.with_score': ', rated',
    'detail.estimated_hours_suffix': 'estimated hours',
    'detail.no_time_yet': 'Time not yet provided',
    'detail.reopen_btn': 'Reopen journey',
    'detail.finish_btn': 'Mark as completed',
    'detail.edit_btn': 'Edit info',
    'detail.overview': 'Overview',
    'detail.review': 'Review',
    'detail.notes': 'Notes',
    'detail.platform': 'Platform',
    'detail.genre': 'Genre',
    'detail.time_to_beat': 'Duration',
    'detail.completion_date': 'Completion',
    'detail.my_rating': 'Rating',
    'detail.platinum': 'Platinum',
    'detail.stat_status': 'Status',
    'detail.stat_time': 'Time',
    'detail.stat_rating': 'Rating',
    'detail.stat_conclusion': 'Completion',
    'detail.stat_open': 'In progress',
    'detail.sheet': 'Journey Details',
    'detail.my_review': 'Your personal review',
    'detail.my_notes': 'Personal notes',
    'detail.move_to': 'Move to',
    'detail.organize': 'Organize your collection',
    'detail.not_informed': 'Not provided',
    'detail.not_informed_m': 'Not provided',
    'detail.no_review_yet': 'Not rated yet',
    'detail.confirm_delete': 'Remove “{nome}” from your collection?',
    'detail.copied': 'Text copied.',
    'detail.share_error': 'Could not share.',
    'detail.moved_to': 'Moved to',

    // Add / Edit Game Modal
    'modal.add_title': 'Add Game',
    'modal.edit_title': 'Edit Game',
    'modal.add_subtitle': 'Fill in the game info',
    'modal.edit_subtitle': 'Update game info',
    'modal.search_igdb': 'Search on IGDB',
    'modal.search_placeholder': 'Type game name...',
    'modal.search_hint': 'Suggestions appear automatically from 2 characters.',
    'modal.searching': 'Searching...',
    'modal.nothing_found': 'Nothing found',
    'modal.cover': 'Cover',
    'modal.cover_change': 'Change',
    'modal.cover_add': 'Add',
    'modal.name': 'Name',
    'modal.name_placeholder': 'Game name',
    'modal.already_in_collection': 'This game is already in your collection',
    'modal.can_add_other_edition': 'You can still add another edition.',
    'modal.status': 'Status',
    'modal.genre': 'Genre',
    'modal.genre_select': 'Select',
    'modal.hours_label': 'Estimated Hours',
    'modal.hours_for_beating': 'h to beat',
    'modal.hours_shortcuts': 'Shortcuts:',
    'modal.platforms': 'Platforms',
    'modal.your_rating': 'Your Rating',
    'modal.rating_hint': 'Click to rate · optional',
    'modal.custom_date': 'Custom date',
    'modal.custom_date_question': 'When did you complete this game?',
    'modal.custom_date_hint': 'Finished on another date? Add here',
    'modal.finished_at': 'Completed on:',
    'modal.platinum_title': 'Platinum / 100% Complete',
    'modal.platinum_desc': 'Check if you achieved 100% of trophies/achievements',
    'modal.tags': 'Custom Tags',
    'modal.notes': 'Notes (Optional)',
    'modal.notes_placeholder': 'Ex: Sequel on PS5; Get trophy X...',
    'modal.save': 'Save Game',
    'modal.save_changes': 'Save Changes',

    // Review Modal
    'review.title': 'Rate Game',
    'review.congrats': 'Congratulations on beating:',
    'review.your_rating': 'Your Rating:',
    'review.rating_instructions': 'Click on the star to select a rating (1 to 10).',
    'review.finished_date': 'Completion date',
    'review.platinum_title': 'Platinum / 100% Complete',
    'review.platinum_desc': 'Unlocked all trophies / achievements',
    'review.comments': 'Review / Comments (Optional)',
    'review.comments_placeholder': 'Ex: A masterpiece! The ending made me cry...',
    'review.finish_btn': 'Complete and Mark as Completed',

    // Stats / Progress Screen
    'stats.journey': 'Your journey',
    'stats.title': 'Statistics',
    'stats.subtitle': 'Your gaming habits translated into numbers.',
    'stats.est_hours': 'Estimated hours',
    'stats.cataloged_games': 'cataloged games',
    'stats.completed_games': 'Completed games',
    'stats.of_collection': 'of collection',
    'stats.avg_score': 'Average rating',
    'stats.rated_between': 'among rated games',
    'stats.platinums': 'Platinums',
    'stats.completed_100': '100% completed games',
    'stats.collection_dist': 'Collection distribution',
    'stats.where_games_are': 'Where your games are now',
    'stats.add_games_hint': 'Add games to view your distribution.',
    'stats.fav_genres': 'Favorite genres',
    'stats.based_on_completed': 'Based on the games you completed',
    'stats.genres_appear_hint': 'Genres will appear once you complete games.',
    'stats.recently_completed': 'Recently completed',
    'stats.recent_achievements': 'Your latest achievements',
    'stats.no_completed_yet': 'No completed games yet.',
    'stats.plat_single': 'Platinum game',
    'stats.plat_multi': 'Platinum games',
    'stats.plat_pct_hint': 'of completed games reached 100%.',
    'stats.games_count': 'games',
    'stats.game_count_single': 'game',

    // Trophies / Enhanced Achievements
    'trophies.subtitle': 'Your collection of feats',
    'trophies.title': 'Trophies',
    'trophies.count_desc': 'achievements unlocked in',
    'trophies.games': 'games.',
    'trophies.tier_platina': 'Platinum',
    'trophies.tier_ouro': 'Gold',
    'trophies.tier_prata': 'Silver',
    'trophies.tier_bronze': 'Bronze',
    'trophies.overall_progress': 'Overall progress',
    'trophies.achievements_waiting': 'achievements still waiting for you.',
    'trophies.earned_xp': 'XP earned',
    'trophies.xp_desc': 'Summing all your unlocked feats.',

    // AI Modal & Badge
    'ai.badge_button': 'AI Soon',
    'ai.badge': 'Coming Soon',
    'ai.title': 'AI Recommendations',
    'ai.headline': 'Soon we will have personalized game recommendations tailored to your taste!',
    'ai.feature1_title': 'Based on what you beat and loved',
    'ai.feature1_desc': 'Analyzes your highest ratings and actual gameplay preferences.',
    'ai.feature2_title': 'Tailored to your free time',
    'ai.feature2_desc': 'Suggests games according to how many hours you have to invest.',
    'ai.feature3_title': 'Discover hidden gems',
    'ai.feature3_desc': 'Great titles you will love and might not even know about.',
    'ai.got_it': 'Got it, can’t wait!',

    // Navigation desktop
    'nav.completed_games': 'completed games',

    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Customize your experience',
    'settings.theme': 'Color Theme',
    'settings.language': 'Language',
    'settings.lang_pt': 'Português (Brasil)',
    'settings.lang_en': 'English',
    'settings.preview': 'Preview',
    'settings.preview_desc': 'This is how your app will look',
    'settings.apply_theme': 'Apply Theme',
    'settings.terms': 'Terms of Use',
    'settings.privacy': 'Privacy Policy',

    // Profile & Public Profile
    'profile.title': 'My Profile',
    'profile.my_profile': 'My Profile',
    'profile.back': 'Back',
    'profile.player_profile': 'Player Profile',
    'profile.edit': 'Edit profile',
    'profile.edit_profile': 'Edit Profile',
    'profile.update_info': 'Update your info',
    'profile.display_name': 'Display name *',
    'profile.name_placeholder': 'Your name in app',
    'profile.bio': 'Bio (optional)',
    'profile.bio_placeholder': 'A sentence about you as a gamer...',
    'profile.email': 'Email (Google)',
    'profile.save_changes': 'Save Changes',
    'profile.logout': 'Sign Out',
    'profile.public_title': 'Public Profile',
    'profile.public_subtitle': 'Share your backlog',
    'profile.your_username': 'Your username',
    'profile.copy_link': 'Copy link',
    'profile.copied': 'Copied!',
    'profile.view_widget': 'View widget',
    'profile.auto_saved': 'Saved automatically',
    'profile.saving': 'Saving...',
    'profile.username_short': 'Username too short (min. 3 chars)',
    'profile.username_taken': 'This username is already taken.',
    'profile.stats_completed': 'Completed',
    'profile.stats_platinums': 'Platinums',
    'profile.stats_avg_rating': 'Avg Rating',
    'profile.stats_hours': 'Hours played',
    'profile.stats_completion': 'Completion rate',
    'profile.favorites': 'Favorites',
    'profile.fav_games': 'Favorite Games',
    'profile.select_favs': 'selected',
    'profile.search_fav': 'Search game…',
    'profile.no_fav_results': 'No results',
    'profile.confirm_selection': 'Confirm Selection',
    'profile.add_favorites': 'Add your favorites',
    'profile.highlight_up_to_5': 'Highlight up to 5 special games',
    'profile.fav_num_1': '⭐ Favorite #1',
    'profile.platinum_badge': '🏆 Platinum',
    'profile.stats': 'Statistics',
    'profile.completion_rate': 'Completion Rate',
    'profile.games_completed_ratio': '{total} games · {finished} completed',
    'profile.highlights': 'Highlights',
    'profile.fav_platform': 'Favorite platform',
    'profile.fav_genre': 'Favorite genre',
    'profile.total_games': 'Total games',
    'profile.avg_rating': 'Average rating',
    'profile.recently_completed': 'Recently Completed',
    'profile.badges_title': 'Badges',
    'profile.badges_unlocked': 'unlocked',
    'profile.theme_btn': 'Theme',
    'profile.theme_btn_sub': 'Customize colors',
    'profile.name_and_bio': 'Name and bio',
    'profile.stat_zerados': 'Completed',
    'profile.stat_total': 'Total',
    'profile.stat_horas': 'Hours',
    'profile.stat_platinas': 'Platinums',
    'profile.stat_notamed': 'Avg. Rating',
    'profile.badges': 'Badges',
    'profile.playing_now': 'Playing now',
    'profile.recent_completed': 'Recently Completed',
    'profile.no_playing': 'No games in progress right now.',
    'profile.no_completed': 'No completed games yet.',
    'profile.not_found': 'Profile not found',
    'profile.not_found_desc': 'The user you are looking for does not exist or changed their name.',
    'profile.create_backlog_cta': 'Create your Backlog too',
    'profile.level': 'Level',
    'profile.next_level_in': 'games to next level',

    // Social / Friends
    'social.title': 'Gamer Community',
    'social.my_code': 'My Friend Code',
    'social.copied': 'Copied!',
    'social.copy': 'Copy',
    'social.tab_friends': 'Friends',
    'social.tab_ranking': 'Ranking',
    'social.tab_feed': 'Feed',
    'social.tab_requests': 'Requests',
    'social.tab_search': 'Search',
    'social.no_friends': 'No friends added yet.',
    'social.add_first_friend': 'Add friends to see their gaming progress!',
    'social.search_placeholder': 'Type friend code...',
    'social.search_btn': 'Search',

    // Common actions
    'action.save': 'Save',
    'action.cancel': 'Cancel',
    'action.close': 'Close',
    'action.search': 'Search games...',
    'action.add_game': 'Add Game',
    'action.filter': 'Filter',

    // Search Modal
    'search.placeholder': 'Search by title, genre, platform...',
    'search.hint': 'Type to search in your collection',
    'search.not_found': 'No games found for',
    'search.not_found_hint': 'Try searching for another term or genre',
    'search.esc_hint': 'ESC to close',

    // Next Game Suggestion
    'next_game.badge': 'Next Game',
    'next_game.very_short': 'Quick',
    'next_game.short': 'Short',
    'next_game.medium': 'Medium',
    'next_game.long': 'Long',
    'next_game.no_estimate': 'No time estimate',
    'next_game.another_suggestion': 'Another suggestion',
    'next_game.play': 'Play',
    'next_game.dismiss': 'Dismiss',

    // All Achievements
    'ach.first_game.title': 'First Victory',
    'ach.first_game.desc': 'Mark your first game as completed.',
    'ach.first_backlog.title': 'Collection Started',
    'ach.first_backlog.desc': 'Add 5 games to your collection.',
    'ach.first_review.title': 'Novice Critic',
    'ach.first_review.desc': 'Rate your first game with a score.',
    'ach.five_games.title': 'Collector Level 1',
    'ach.five_games.desc': 'Beat 5 games in total.',
    'ach.ten_games.title': 'Veteran',
    'ach.ten_games.desc': 'Beat 10 games in total.',
    'ach.twenty_five_games.title': 'Endings Hunter',
    'ach.twenty_five_games.desc': 'Beat 25 games in total.',
    'ach.fifty_games.title': 'Legendary',
    'ach.fifty_games.desc': 'Beat 50 games. A living legend.',
    'ach.full_backlog.title': 'Full Backlog',
    'ach.full_backlog.desc': 'Have 15 or more games listed.',
    'ach.wishlist_10.title': 'Dreamer',
    'ach.wishlist_10.desc': 'Add 10 games to your wishlist.',
    'ach.queue_buster.title': 'Queue Buster',
    'ach.queue_buster.desc': 'Have 20+ games between backlog and installed.',
    'ach.multi_platform.title': 'Multi-platform Gamer',
    'ach.multi_platform.desc': 'Beat games on 3 different platforms.',
    'ach.first_platinum.title': 'Completionist',
    'ach.first_platinum.desc': 'Earn your first platinum.',
    'ach.five_platinums.title': 'Platinum Hunter',
    'ach.five_platinums.desc': 'Earn 5 platinums.',
    'ach.ten_platinums.title': '100% Master',
    'ach.ten_platinums.desc': 'Earn 10 platinums.',
    'ach.perfect_score.title': 'Masterpiece',
    'ach.perfect_score.desc': 'Give a 10 rating to a game.',
    'ach.three_perfect.title': 'Demanding Critic',
    'ach.three_perfect.desc': 'Give a 10 rating to 3 games.',
    'ach.average_8.title': 'Great Taste',
    'ach.average_8.desc': 'Maintain average score ≥ 8 with 5+ ratings.',
    'ach.honest_critic.title': 'Honest Critic',
    'ach.honest_critic.desc': 'Give a score ≤ 4 to a game.',
    'ach.rpg_master.title': 'RPG Master',
    'ach.rpg_master.desc': 'Beat 3 RPG games.',
    'ach.action_hero.title': 'Action Hero',
    'ach.action_hero.desc': 'Beat 3 Action games.',
    'ach.fps_soldier.title': 'FPS Soldier',
    'ach.fps_soldier.desc': 'Beat 3 FPS games.',
    'ach.genre_master.title': 'Genre Specialist',
    'ach.genre_master.desc': 'Beat 5 games of the same genre.',
    'ach.fifty_hours.title': 'Dedicated',
    'ach.fifty_hours.desc': 'Accumulate 50 hours in completed games.',
    'ach.two_hundred_hours.title': 'Marathoner',
    'ach.two_hundred_hours.desc': 'Accumulate 200 hours in completed games.',
    'ach.five_hundred_hours.title': 'No-Lifer',
    'ach.five_hundred_hours.desc': 'Accumulate 500 hours in completed games.',
    'ach.one_thousand_hours.title': 'The Chosen One',
    'ach.one_thousand_hours.desc': 'Accumulate 1000 hours of journey.',

    // Landing / Login
    'landing.security_badge': 'Your data safely synchronized',
    'landing.badge': 'Your next adventure starts here',
    'landing.headline_1': 'Less time deciding.',
    'landing.headline_grad': 'More time playing.',
    'landing.subtitle': 'Organize your collection, track achievements, and find the right game for every moment — without turning fun into a spreadsheet.',
    'landing.bullet1': 'Backlog in one place',
    'landing.bullet2': 'Automatic statistics',
    'landing.bullet3': 'Personalized suggestions',
    'landing.continue_google': 'Continue with Google',
    'landing.login_note': 'Fast and secure login. No extra passwords to remember.',
    'landing.panel_title': 'Your dashboard',
    'landing.panel_subtitle': 'Everything under control',
    'landing.panel_games_count': '24 games',
    'landing.status_playing': 'Playing',
    'landing.status_queue': 'In queue',
    'landing.status_completed': 'Completed',
    'landing.feat1_title': 'Organized backlog',
    'landing.feat1_desc': 'Everything you want to play, without losing context.',
    'landing.feat2_title': 'Visible progress',
    'landing.feat2_desc': 'Goals, history and statistics all in one place.',
    'landing.feat3_title': 'Easier choices',
    'landing.feat3_desc': 'Smart suggestions to decide your next game.',
    'landing.copyright': '© {year} XpLog. All rights reserved.',
    'landing.terms': 'Terms of Use',
    'landing.privacy': 'Privacy Policy',
  }
};

export const GENRE_MAP = {
  'Ação': { 'pt-BR': 'Ação', 'en': 'Action' },
  'Action': { 'pt-BR': 'Ação', 'en': 'Action' },
  'Aventura': { 'pt-BR': 'Aventura', 'en': 'Adventure' },
  'Adventure': { 'pt-BR': 'Aventura', 'en': 'Adventure' },
  'RPG': { 'pt-BR': 'RPG', 'en': 'RPG' },
  'Plataforma': { 'pt-BR': 'Plataforma', 'en': 'Platformer' },
  'Platform': { 'pt-BR': 'Plataforma', 'en': 'Platformer' },
  'Platformer': { 'pt-BR': 'Plataforma', 'en': 'Platformer' },
  'FPS': { 'pt-BR': 'FPS', 'en': 'FPS' },
  'Tiro / FPS': { 'pt-BR': 'Tiro / FPS', 'en': 'Shooter / FPS' },
  'Shooter': { 'pt-BR': 'Tiro / FPS', 'en': 'Shooter' },
  'Estratégia': { 'pt-BR': 'Estratégia', 'en': 'Strategy' },
  'Strategy': { 'pt-BR': 'Estratégia', 'en': 'Strategy' },
  'Roguelite': { 'pt-BR': 'Roguelite', 'en': 'Roguelite' },
  'Roguelike': { 'pt-BR': 'Roguelike', 'en': 'Roguelike' },
  'Simulação': { 'pt-BR': 'Simulação', 'en': 'Simulation' },
  'Simulator': { 'pt-BR': 'Simulação', 'en': 'Simulation' },
  'Simulation': { 'pt-BR': 'Simulação', 'en': 'Simulation' },
  'Puzzle': { 'pt-BR': 'Puzzle', 'en': 'Puzzle' },
  'Quebra-cabeça': { 'pt-BR': 'Puzzle', 'en': 'Puzzle' },
  'Terror': { 'pt-BR': 'Terror', 'en': 'Horror' },
  'Horror': { 'pt-BR': 'Terror', 'en': 'Horror' },
  'Terror / Horror': { 'pt-BR': 'Terror / Horror', 'en': 'Horror' },
  'Corrida': { 'pt-BR': 'Corrida', 'en': 'Racing' },
  'Racing': { 'pt-BR': 'Corrida', 'en': 'Racing' },
  'Luta': { 'pt-BR': 'Luta', 'en': 'Fighting' },
  'Fighting': { 'pt-BR': 'Luta', 'en': 'Fighting' },
  'Esportes': { 'pt-BR': 'Esportes', 'en': 'Sports' },
  'Sports': { 'pt-BR': 'Esportes', 'en': 'Sports' },
  'Outro': { 'pt-BR': 'Outro', 'en': 'Other' },
  'Outra': { 'pt-BR': 'Outra', 'en': 'Other' },
  'Other': { 'pt-BR': 'Outro', 'en': 'Other' },
};

export function getTranslatedGenre(genre, language = 'pt-BR') {
  if (!genre) return '';
  const match = GENRE_MAP[genre];
  if (match) {
    return match[language] || match['pt-BR'] || genre;
  }
  return genre;
}

const STORAGE_KEY = 'xplog_language';

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    try {
      const local = localStorage.getItem(STORAGE_KEY);
      if (local === 'en' || local === 'pt-BR') return local;
    } catch {
      // ignore
    }
    return 'pt-BR';
  });

  useEffect(() => {
    const unsub = auth.onAuthStateChanged(async (u) => {
      if (u?.uid) {
        try {
          const snap = await getDoc(doc(db, 'users', u.uid));
          if (snap.exists()) {
            const userLang = snap.data()?.language;
            if (userLang && (userLang === 'pt-BR' || userLang === 'en')) {
              setLanguageState(userLang);
              try {
                localStorage.setItem(STORAGE_KEY, userLang);
              } catch {
                // ignore
              }
            }
          }
        } catch (err) {
          console.warn('Erro ao carregar preferência de idioma do Firestore:', err);
        }
      }
    });
    return () => unsub();
  }, []);

  const changeLanguage = useCallback(async (newLang) => {
    if (newLang !== 'pt-BR' && newLang !== 'en') return;
    setLanguageState(newLang);
    try {
      localStorage.setItem(STORAGE_KEY, newLang);
    } catch {
      // ignore
    }

    const currentUid = auth.currentUser?.uid;
    if (currentUid) {
      try {
        await updateDoc(doc(db, 'users', currentUid), {
          language: newLang,
        });
      } catch (err) {
        console.warn('Não foi possível salvar a preferência de idioma no Firestore:', err);
      }
    }
  }, []);

  const t = useCallback((key, params = {}) => {
    let str = TRANSLATIONS[language]?.[key] ?? TRANSLATIONS['pt-BR']?.[key] ?? key;
    if (params && typeof params === 'object') {
      Object.entries(params).forEach(([paramKey, paramVal]) => {
        str = str.replace(new RegExp(`\\{${paramKey}\\}`, 'g'), paramVal);
      });
    }
    return str;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    return {
      language: 'pt-BR',
      setLanguage: () => {},
      t: (k, params = {}) => {
        let str = TRANSLATIONS['pt-BR']?.[k] ?? k;
        if (params && typeof params === 'object') {
          Object.entries(params).forEach(([paramKey, paramVal]) => {
            str = str.replace(new RegExp(`\\{${paramKey}\\}`, 'g'), paramVal);
          });
        }
        return str;
      },
    };
  }
  return ctx;
}
